### ISSUE TITLE
Great socialite plugin

### ISSUE THREAD

**Issue by jeubis** [BePark/socialite-azure-oauth#1]
Hey @jeremy379,

Thanks for putting this together, it is definitely the most extensible ms socialite plugin, it is a bit of a shame it isn't in their website.

I have a question in regards to this though, I am slightly confused as I can't redirect back to my front-end application once I have finished my custom override.

Please see below:

```
<?php

namespace App\Http\Controllers\Auth;

use App\Http\Controllers\Auth\AuthController;
use Bepark\SocialiteAzureOAuth\AzureOAuthControllerTrait;
use App\User;

use Log;
use Auth;
use JWTAuth;
use Redirect;

class OAuthController extends AuthController
{
    use AzureOAuthControllerTrait;
    
    public function handleOauthUser($user)
    {
        $registered = $this->users->check($user->email);
        try {
            if ($registered) {
                $this->getExistingUser($registered);
            } else {
                $this->createNewUser($user);
            }
        } catch (Exception $e) {
            Log::error("User unable to create service account. UID =" . $user->uid . "Message =" . $e->getMessage());
            abort(400, $e->getMessage());
        }
    }

    public function getExistingUser($user) {
        $serviceUser = $this->getOrCreateServiceUser($user);

        $user->access_key = $serviceUser->keys[0]->access_key;
        $user->secret_key = $serviceUser->keys[0]->secret_key;

        $this->users->updateAccessKeys((object) $user);
        
        Auth::login($user);
        
        $sessionUser = Auth::User();
        $sessionUser['token'] = JWTAuth::fromUser($user);

        if (env('APP_ENV') === 'local') {
            return redirect()->away('http://localhost:3000');
        }
        return redirect();    
    }

    public function createNewUser($user) {
        $user->uid = $user->email;
        $user->role = 'user';
        
        $someService = $this->getOrCreateServiceUser($user);

        $user->access_key = $someService->keys[0]->access_key;
        $user->secret_key = $someService->keys[0]->secret_key;
        
        $created = $this->users->createUser((array) $user);

        Auth::login($created);
        $sessionUser = Auth::User();

        $sessionUser['token'] = JWTAuth::fromUser($user);
        
        if (env('APP_ENV') === 'local') {
            return redirect()->away('http://localhost:3000/');
        }
        return redirect('/');
    }
}
```

Any ideas on what I am doing incorrect? I understand the redirect is a global function which should just "work" and I know that it is calling the redirect.

**Comment by jeremy379** [comment]
Hi
Thank you, I did it mostly for my project and I'm glad it can also help other developers.

So if you dd() just before the redirect it is displayed? 

Take care in the getExistingUser() method, the redirect if not local has no argument.

Did you also try to redirect to an internal route (Personally I use `return redirect()->route('my.route.name')`

Basically if you do a `dd($user)` in handleOauthUser() method and you see all your expected data, the integration with azure is working and the issue may come from something else related to your Laravel integration.

**Comment by jeubis** [comment]
Hey! thanks for getting back to me so quickly.

That's awesome, you should try and submit it to them as it gives you a lot but allows you to override anything you need.

So your entire flow works as expected and I am able to create the user inside of the handleOAuthUser The main issue I am facing is when I call the redirect function it doesn't redirect in the browser and I can't see any more requests being made. I am using laravel 5.5.

I've also had a look at the Laracast on Socialite and they just use the redirect function so TBH I am just super confused and wondering whether you had any suggestions or if there was some intricacy of the Socalite Provider I am missing. 
```
the redirect if not local has no argument.
```
Yes I just saw haha. I am only developing locally so that's why it's ok for now but I will update.

**Comment by jeubis** [comment]
I figured it out. I wasn't returning to the inner function so it must just ignore it. Damn that was an expensive and painful experience. 

Anyways thanks!
